//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bathsTotal",
    "bathsFull",
    "bathsHalf",
    "bathsThreeQuarter"
})
@XmlRootElement(name = "Baths")
public class Baths {

    @XmlElement(name = "BathsTotal")
    protected BathsTotal bathsTotal;
    @XmlElement(name = "BathsFull")
    protected BathsFull bathsFull;
    @XmlElement(name = "BathsHalf")
    protected BathsHalf bathsHalf;
    @XmlElement(name = "BathsThreeQuarter")
    protected BathsThreeQuarter bathsThreeQuarter;

    /**
     * Gets the value of the bathsTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BathsTotal }
     *     
     */
    public BathsTotal getBathsTotal() {
        return bathsTotal;
    }

    /**
     * Sets the value of the bathsTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BathsTotal }
     *     
     */
    public void setBathsTotal(BathsTotal value) {
        this.bathsTotal = value;
    }

    /**
     * Gets the value of the bathsFull property.
     * 
     * @return
     *     possible object is
     *     {@link BathsFull }
     *     
     */
    public BathsFull getBathsFull() {
        return bathsFull;
    }

    /**
     * Sets the value of the bathsFull property.
     * 
     * @param value
     *     allowed object is
     *     {@link BathsFull }
     *     
     */
    public void setBathsFull(BathsFull value) {
        this.bathsFull = value;
    }

    /**
     * Gets the value of the bathsHalf property.
     * 
     * @return
     *     possible object is
     *     {@link BathsHalf }
     *     
     */
    public BathsHalf getBathsHalf() {
        return bathsHalf;
    }

    /**
     * Sets the value of the bathsHalf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BathsHalf }
     *     
     */
    public void setBathsHalf(BathsHalf value) {
        this.bathsHalf = value;
    }

    /**
     * Gets the value of the bathsThreeQuarter property.
     * 
     * @return
     *     possible object is
     *     {@link BathsThreeQuarter }
     *     
     */
    public BathsThreeQuarter getBathsThreeQuarter() {
        return bathsThreeQuarter;
    }

    /**
     * Sets the value of the bathsThreeQuarter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BathsThreeQuarter }
     *     
     */
    public void setBathsThreeQuarter(BathsThreeQuarter value) {
        this.bathsThreeQuarter = value;
    }

}
