//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "residentialProperty",
    "complex"
})
@XmlRootElement(name = "CommonInterest")
public class CommonInterest {

    @XmlElement(name = "ResidentialProperty")
    protected ResidentialProperty residentialProperty;
    @XmlElement(name = "Complex")
    protected Complex complex;

    /**
     * Gets the value of the residentialProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ResidentialProperty }
     *     
     */
    public ResidentialProperty getResidentialProperty() {
        return residentialProperty;
    }

    /**
     * Sets the value of the residentialProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidentialProperty }
     *     
     */
    public void setResidentialProperty(ResidentialProperty value) {
        this.residentialProperty = value;
    }

    /**
     * Gets the value of the complex property.
     * 
     * @return
     *     possible object is
     *     {@link Complex }
     *     
     */
    public Complex getComplex() {
        return complex;
    }

    /**
     * Sets the value of the complex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Complex }
     *     
     */
    public void setComplex(Complex value) {
        this.complex = value;
    }

}
