//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "streetAddress",
    "listingData",
    "mlsInformation",
    "geographicData",
    "modificationTimestamp",
    "listingID",
    "zoning",
    "salesData",
    "schoolData",
    "taxData",
    "parcelNumber",
    "view",
    "copyrightNotice",
    "disclaimer",
    "pictureData"
})
@XmlRootElement(name = "Listing")
public class Listing {

    @XmlElement(name = "StreetAddress")
    protected StreetAddress streetAddress;
    @XmlElement(name = "ListingData")
    protected ListingData listingData;
    @XmlElement(name = "MLSInformation")
    protected MLSInformation mlsInformation;
    @XmlElement(name = "GeographicData")
    protected GeographicData geographicData;
    @XmlElement(name = "ModificationTimestamp")
    protected ModificationTimestamp modificationTimestamp;
    @XmlElement(name = "ListingID")
    protected ListingID listingID;
    @XmlElement(name = "Zoning")
    protected String zoning;
    @XmlElement(name = "SalesData")
    protected SalesData salesData;
    @XmlElement(name = "SchoolData")
    protected SchoolData schoolData;
    @XmlElement(name = "TaxData")
    protected TaxData taxData;
    @XmlElement(name = "ParcelNumber")
    protected String parcelNumber;
    @XmlElement(name = "View")
    protected View view;
    @XmlElement(name = "CopyrightNotice")
    protected String copyrightNotice;
    @XmlElement(name = "Disclaimer")
    protected String disclaimer;
    @XmlElement(name = "PictureData")
    protected List<PictureData> pictureData;

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link StreetAddress }
     *     
     */
    public StreetAddress getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetAddress }
     *     
     */
    public void setStreetAddress(StreetAddress value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the listingData property.
     * 
     * @return
     *     possible object is
     *     {@link ListingData }
     *     
     */
    public ListingData getListingData() {
        return listingData;
    }

    /**
     * Sets the value of the listingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingData }
     *     
     */
    public void setListingData(ListingData value) {
        this.listingData = value;
    }

    /**
     * Gets the value of the mlsInformation property.
     * 
     * @return
     *     possible object is
     *     {@link MLSInformation }
     *     
     */
    public MLSInformation getMLSInformation() {
        return mlsInformation;
    }

    /**
     * Sets the value of the mlsInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLSInformation }
     *     
     */
    public void setMLSInformation(MLSInformation value) {
        this.mlsInformation = value;
    }

    /**
     * Gets the value of the geographicData property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicData }
     *     
     */
    public GeographicData getGeographicData() {
        return geographicData;
    }

    /**
     * Sets the value of the geographicData property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicData }
     *     
     */
    public void setGeographicData(GeographicData value) {
        this.geographicData = value;
    }

    /**
     * Gets the value of the modificationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationTimestamp }
     *     
     */
    public ModificationTimestamp getModificationTimestamp() {
        return modificationTimestamp;
    }

    /**
     * Sets the value of the modificationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationTimestamp }
     *     
     */
    public void setModificationTimestamp(ModificationTimestamp value) {
        this.modificationTimestamp = value;
    }

    /**
     * Gets the value of the listingID property.
     * 
     * @return
     *     possible object is
     *     {@link ListingID }
     *     
     */
    public ListingID getListingID() {
        return listingID;
    }

    /**
     * Sets the value of the listingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingID }
     *     
     */
    public void setListingID(ListingID value) {
        this.listingID = value;
    }

    /**
     * Gets the value of the zoning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoning() {
        return zoning;
    }

    /**
     * Sets the value of the zoning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoning(String value) {
        this.zoning = value;
    }

    /**
     * Gets the value of the salesData property.
     * 
     * @return
     *     possible object is
     *     {@link SalesData }
     *     
     */
    public SalesData getSalesData() {
        return salesData;
    }

    /**
     * Sets the value of the salesData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesData }
     *     
     */
    public void setSalesData(SalesData value) {
        this.salesData = value;
    }

    /**
     * Gets the value of the schoolData property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolData }
     *     
     */
    public SchoolData getSchoolData() {
        return schoolData;
    }

    /**
     * Sets the value of the schoolData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolData }
     *     
     */
    public void setSchoolData(SchoolData value) {
        this.schoolData = value;
    }

    /**
     * Gets the value of the taxData property.
     * 
     * @return
     *     possible object is
     *     {@link TaxData }
     *     
     */
    public TaxData getTaxData() {
        return taxData;
    }

    /**
     * Sets the value of the taxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxData }
     *     
     */
    public void setTaxData(TaxData value) {
        this.taxData = value;
    }

    /**
     * Gets the value of the parcelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelNumber() {
        return parcelNumber;
    }

    /**
     * Sets the value of the parcelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelNumber(String value) {
        this.parcelNumber = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link View }
     *     
     */
    public View getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link View }
     *     
     */
    public void setView(View value) {
        this.view = value;
    }

    /**
     * Gets the value of the copyrightNotice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightNotice() {
        return copyrightNotice;
    }

    /**
     * Sets the value of the copyrightNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightNotice(String value) {
        this.copyrightNotice = value;
    }

    /**
     * Gets the value of the disclaimer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimer() {
        return disclaimer;
    }

    /**
     * Sets the value of the disclaimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimer(String value) {
        this.disclaimer = value;
    }

    /**
     * Gets the value of the pictureData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pictureData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPictureData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PictureData }
     * 
     * 
     */
    public List<PictureData> getPictureData() {
        if (pictureData == null) {
            pictureData = new ArrayList<PictureData>();
        }
        return this.pictureData;
    }

}
