//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listingStatus",
    "originalListPrice",
    "listingArea",
    "statusChangeDate",
    "daysOnMarket",
    "listingServiceName"
})
@XmlRootElement(name = "MLSInformation")
public class MLSInformation {

    @XmlElement(name = "ListingStatus")
    protected ListingStatus listingStatus;
    @XmlElement(name = "OriginalListPrice")
    protected OriginalListPrice originalListPrice;
    @XmlElement(name = "ListingArea")
    protected String listingArea;
    @XmlElement(name = "StatusChangeDate")
    protected StatusChangeDate statusChangeDate;
    @XmlElement(name = "DaysOnMarket")
    protected DaysOnMarket daysOnMarket;
    @XmlElement(name = "ListingServiceName")
    protected String listingServiceName;

    /**
     * Gets the value of the listingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ListingStatus }
     *     
     */
    public ListingStatus getListingStatus() {
        return listingStatus;
    }

    /**
     * Sets the value of the listingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingStatus }
     *     
     */
    public void setListingStatus(ListingStatus value) {
        this.listingStatus = value;
    }

    /**
     * Gets the value of the originalListPrice property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalListPrice }
     *     
     */
    public OriginalListPrice getOriginalListPrice() {
        return originalListPrice;
    }

    /**
     * Sets the value of the originalListPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalListPrice }
     *     
     */
    public void setOriginalListPrice(OriginalListPrice value) {
        this.originalListPrice = value;
    }

    /**
     * Gets the value of the listingArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListingArea() {
        return listingArea;
    }

    /**
     * Sets the value of the listingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListingArea(String value) {
        this.listingArea = value;
    }

    /**
     * Gets the value of the statusChangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link StatusChangeDate }
     *     
     */
    public StatusChangeDate getStatusChangeDate() {
        return statusChangeDate;
    }

    /**
     * Sets the value of the statusChangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusChangeDate }
     *     
     */
    public void setStatusChangeDate(StatusChangeDate value) {
        this.statusChangeDate = value;
    }

    /**
     * Gets the value of the daysOnMarket property.
     * 
     * @return
     *     possible object is
     *     {@link DaysOnMarket }
     *     
     */
    public DaysOnMarket getDaysOnMarket() {
        return daysOnMarket;
    }

    /**
     * Sets the value of the daysOnMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysOnMarket }
     *     
     */
    public void setDaysOnMarket(DaysOnMarket value) {
        this.daysOnMarket = value;
    }

    /**
     * Gets the value of the listingServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListingServiceName() {
        return listingServiceName;
    }

    /**
     * Sets the value of the listingServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListingServiceName(String value) {
        this.listingServiceName = value;
    }

}
