//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listing",
    "complex",
    "rentIncome",
    "grossIncome",
    "expenses",
    "netIncome",
    "vacancyFactor",
    "tenantPays",
    "ownerPays",
    "laundry",
    "subdivision",
    "associationFee",
    "livingArea",
    "lotSize",
    "parking",
    "stories",
    "yearBuilt",
    "heating",
    "cooling",
    "pool",
    "interiorFeatures",
    "exteriorFeatures",
    "type",
    "style",
    "waterFront",
    "roof",
    "exterior",
    "unit"
})
@XmlRootElement(name = "MultiFamily")
public class MultiFamily {

    @XmlElement(name = "Listing")
    protected Listing listing;
    @XmlElement(name = "Complex")
    protected Complex complex;
    @XmlElement(name = "RentIncome")
    protected RentIncome rentIncome;
    @XmlElement(name = "GrossIncome")
    protected GrossIncome grossIncome;
    @XmlElement(name = "Expenses")
    protected Expenses expenses;
    @XmlElement(name = "NetIncome")
    protected NetIncome netIncome;
    @XmlElement(name = "VacancyFactor")
    protected VacancyFactor vacancyFactor;
    @XmlElement(name = "TenantPays")
    protected String tenantPays;
    @XmlElement(name = "OwnerPays")
    protected String ownerPays;
    @XmlElement(name = "Laundry")
    protected Laundry laundry;
    @XmlElement(name = "Subdivision")
    protected String subdivision;
    @XmlElement(name = "AssociationFee")
    protected AssociationFee associationFee;
    @XmlElement(name = "LivingArea")
    protected LivingArea livingArea;
    @XmlElement(name = "LotSize")
    protected LotSize lotSize;
    @XmlElement(name = "Parking")
    protected Parking parking;
    @XmlElement(name = "Stories")
    protected Stories stories;
    @XmlElement(name = "YearBuilt")
    protected YearBuilt yearBuilt;
    @XmlElement(name = "Heating")
    protected Heating heating;
    @XmlElement(name = "Cooling")
    protected Cooling cooling;
    @XmlElement(name = "Pool")
    protected Pool pool;
    @XmlElement(name = "InteriorFeatures")
    protected String interiorFeatures;
    @XmlElement(name = "ExteriorFeatures")
    protected String exteriorFeatures;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "Style")
    protected String style;
    @XmlElement(name = "WaterFront")
    protected WaterFront waterFront;
    @XmlElement(name = "Roof")
    protected String roof;
    @XmlElement(name = "Exterior")
    protected String exterior;
    @XmlElement(name = "Unit")
    protected List<Unit> unit;

    /**
     * Gets the value of the listing property.
     * 
     * @return
     *     possible object is
     *     {@link Listing }
     *     
     */
    public Listing getListing() {
        return listing;
    }

    /**
     * Sets the value of the listing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Listing }
     *     
     */
    public void setListing(Listing value) {
        this.listing = value;
    }

    /**
     * Gets the value of the complex property.
     * 
     * @return
     *     possible object is
     *     {@link Complex }
     *     
     */
    public Complex getComplex() {
        return complex;
    }

    /**
     * Sets the value of the complex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Complex }
     *     
     */
    public void setComplex(Complex value) {
        this.complex = value;
    }

    /**
     * Gets the value of the rentIncome property.
     * 
     * @return
     *     possible object is
     *     {@link RentIncome }
     *     
     */
    public RentIncome getRentIncome() {
        return rentIncome;
    }

    /**
     * Sets the value of the rentIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link RentIncome }
     *     
     */
    public void setRentIncome(RentIncome value) {
        this.rentIncome = value;
    }

    /**
     * Gets the value of the grossIncome property.
     * 
     * @return
     *     possible object is
     *     {@link GrossIncome }
     *     
     */
    public GrossIncome getGrossIncome() {
        return grossIncome;
    }

    /**
     * Sets the value of the grossIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrossIncome }
     *     
     */
    public void setGrossIncome(GrossIncome value) {
        this.grossIncome = value;
    }

    /**
     * Gets the value of the expenses property.
     * 
     * @return
     *     possible object is
     *     {@link Expenses }
     *     
     */
    public Expenses getExpenses() {
        return expenses;
    }

    /**
     * Sets the value of the expenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expenses }
     *     
     */
    public void setExpenses(Expenses value) {
        this.expenses = value;
    }

    /**
     * Gets the value of the netIncome property.
     * 
     * @return
     *     possible object is
     *     {@link NetIncome }
     *     
     */
    public NetIncome getNetIncome() {
        return netIncome;
    }

    /**
     * Sets the value of the netIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetIncome }
     *     
     */
    public void setNetIncome(NetIncome value) {
        this.netIncome = value;
    }

    /**
     * Gets the value of the vacancyFactor property.
     * 
     * @return
     *     possible object is
     *     {@link VacancyFactor }
     *     
     */
    public VacancyFactor getVacancyFactor() {
        return vacancyFactor;
    }

    /**
     * Sets the value of the vacancyFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VacancyFactor }
     *     
     */
    public void setVacancyFactor(VacancyFactor value) {
        this.vacancyFactor = value;
    }

    /**
     * Gets the value of the tenantPays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantPays() {
        return tenantPays;
    }

    /**
     * Sets the value of the tenantPays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantPays(String value) {
        this.tenantPays = value;
    }

    /**
     * Gets the value of the ownerPays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerPays() {
        return ownerPays;
    }

    /**
     * Sets the value of the ownerPays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerPays(String value) {
        this.ownerPays = value;
    }

    /**
     * Gets the value of the laundry property.
     * 
     * @return
     *     possible object is
     *     {@link Laundry }
     *     
     */
    public Laundry getLaundry() {
        return laundry;
    }

    /**
     * Sets the value of the laundry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Laundry }
     *     
     */
    public void setLaundry(Laundry value) {
        this.laundry = value;
    }

    /**
     * Gets the value of the subdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdivision() {
        return subdivision;
    }

    /**
     * Sets the value of the subdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdivision(String value) {
        this.subdivision = value;
    }

    /**
     * Gets the value of the associationFee property.
     * 
     * @return
     *     possible object is
     *     {@link AssociationFee }
     *     
     */
    public AssociationFee getAssociationFee() {
        return associationFee;
    }

    /**
     * Sets the value of the associationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociationFee }
     *     
     */
    public void setAssociationFee(AssociationFee value) {
        this.associationFee = value;
    }

    /**
     * Gets the value of the livingArea property.
     * 
     * @return
     *     possible object is
     *     {@link LivingArea }
     *     
     */
    public LivingArea getLivingArea() {
        return livingArea;
    }

    /**
     * Sets the value of the livingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link LivingArea }
     *     
     */
    public void setLivingArea(LivingArea value) {
        this.livingArea = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link LotSize }
     *     
     */
    public LotSize getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotSize }
     *     
     */
    public void setLotSize(LotSize value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     * @return
     *     possible object is
     *     {@link Parking }
     *     
     */
    public Parking getParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parking }
     *     
     */
    public void setParking(Parking value) {
        this.parking = value;
    }

    /**
     * Gets the value of the stories property.
     * 
     * @return
     *     possible object is
     *     {@link Stories }
     *     
     */
    public Stories getStories() {
        return stories;
    }

    /**
     * Sets the value of the stories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stories }
     *     
     */
    public void setStories(Stories value) {
        this.stories = value;
    }

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link YearBuilt }
     *     
     */
    public YearBuilt getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearBuilt }
     *     
     */
    public void setYearBuilt(YearBuilt value) {
        this.yearBuilt = value;
    }

    /**
     * Gets the value of the heating property.
     * 
     * @return
     *     possible object is
     *     {@link Heating }
     *     
     */
    public Heating getHeating() {
        return heating;
    }

    /**
     * Sets the value of the heating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heating }
     *     
     */
    public void setHeating(Heating value) {
        this.heating = value;
    }

    /**
     * Gets the value of the cooling property.
     * 
     * @return
     *     possible object is
     *     {@link Cooling }
     *     
     */
    public Cooling getCooling() {
        return cooling;
    }

    /**
     * Sets the value of the cooling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cooling }
     *     
     */
    public void setCooling(Cooling value) {
        this.cooling = value;
    }

    /**
     * Gets the value of the pool property.
     * 
     * @return
     *     possible object is
     *     {@link Pool }
     *     
     */
    public Pool getPool() {
        return pool;
    }

    /**
     * Sets the value of the pool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pool }
     *     
     */
    public void setPool(Pool value) {
        this.pool = value;
    }

    /**
     * Gets the value of the interiorFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteriorFeatures() {
        return interiorFeatures;
    }

    /**
     * Sets the value of the interiorFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteriorFeatures(String value) {
        this.interiorFeatures = value;
    }

    /**
     * Gets the value of the exteriorFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExteriorFeatures() {
        return exteriorFeatures;
    }

    /**
     * Sets the value of the exteriorFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExteriorFeatures(String value) {
        this.exteriorFeatures = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the waterFront property.
     * 
     * @return
     *     possible object is
     *     {@link WaterFront }
     *     
     */
    public WaterFront getWaterFront() {
        return waterFront;
    }

    /**
     * Sets the value of the waterFront property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaterFront }
     *     
     */
    public void setWaterFront(WaterFront value) {
        this.waterFront = value;
    }

    /**
     * Gets the value of the roof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoof() {
        return roof;
    }

    /**
     * Sets the value of the roof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoof(String value) {
        this.roof = value;
    }

    /**
     * Gets the value of the exterior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExterior() {
        return exterior;
    }

    /**
     * Sets the value of the exterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExterior(String value) {
        this.exterior = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Unit }
     * 
     * 
     */
    public List<Unit> getUnit() {
        if (unit == null) {
            unit = new ArrayList<Unit>();
        }
        return this.unit;
    }

}
