//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListDate }
     * 
     */
    public ListDate createListDate() {
        return new ListDate();
    }

    /**
     * Create an instance of {@link Garage }
     * 
     */
    public Garage createGarage() {
        return new Garage();
    }

    /**
     * Create an instance of {@link RentIncome }
     * 
     */
    public RentIncome createRentIncome() {
        return new RentIncome();
    }

    /**
     * Create an instance of {@link EndDateTime }
     * 
     */
    public EndDateTime createEndDateTime() {
        return new EndDateTime();
    }

    /**
     * Create an instance of {@link OpenParking }
     * 
     */
    public OpenParking createOpenParking() {
        return new OpenParking();
    }

    /**
     * Create an instance of {@link ActivityClassification }
     * 
     */
    public ActivityClassification createActivityClassification() {
        return new ActivityClassification();
    }

    /**
     * Create an instance of {@link LivingRoom }
     * 
     */
    public LivingRoom createLivingRoom() {
        return new LivingRoom();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link Length }
     * 
     */
    public Length createLength() {
        return new Length();
    }

    /**
     * Create an instance of {@link Width }
     * 
     */
    public Width createWidth() {
        return new Width();
    }

    /**
     * Create an instance of {@link Utilities }
     * 
     */
    public Utilities createUtilities() {
        return new Utilities();
    }

    /**
     * Create an instance of {@link Laundry }
     * 
     */
    public Laundry createLaundry() {
        return new Laundry();
    }

    /**
     * Create an instance of {@link StreetDirPrefix }
     * 
     */
    public StreetDirPrefix createStreetDirPrefix() {
        return new StreetDirPrefix();
    }

    /**
     * Create an instance of {@link Expenses }
     * 
     */
    public Expenses createExpenses() {
        return new Expenses();
    }

    /**
     * Create an instance of {@link REAgent }
     * 
     */
    public REAgent createREAgent() {
        return new REAgent();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link StreetAddress }
     * 
     */
    public StreetAddress createStreetAddress() {
        return new StreetAddress();
    }

    /**
     * Create an instance of {@link AgentID }
     * 
     */
    public AgentID createAgentID() {
        return new AgentID();
    }

    /**
     * Create an instance of {@link OfficeID }
     * 
     */
    public OfficeID createOfficeID() {
        return new OfficeID();
    }

    /**
     * Create an instance of {@link ModificationTimestamp }
     * 
     */
    public ModificationTimestamp createModificationTimestamp() {
        return new ModificationTimestamp();
    }

    /**
     * Create an instance of {@link CarrierRoute }
     * 
     */
    public CarrierRoute createCarrierRoute() {
        return new CarrierRoute();
    }

    /**
     * Create an instance of {@link Parking }
     * 
     */
    public Parking createParking() {
        return new Parking();
    }

    /**
     * Create an instance of {@link CarPort }
     * 
     */
    public CarPort createCarPort() {
        return new CarPort();
    }

    /**
     * Create an instance of {@link CoveredParking }
     * 
     */
    public CoveredParking createCoveredParking() {
        return new CoveredParking();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link DiningRoom }
     * 
     */
    public DiningRoom createDiningRoom() {
        return new DiningRoom();
    }

    /**
     * Create an instance of {@link FamilyRoom }
     * 
     */
    public FamilyRoom createFamilyRoom() {
        return new FamilyRoom();
    }

    /**
     * Create an instance of {@link Basement }
     * 
     */
    public Basement createBasement() {
        return new Basement();
    }

    /**
     * Create an instance of {@link TotalRooms }
     * 
     */
    public TotalRooms createTotalRooms() {
        return new TotalRooms();
    }

    /**
     * Create an instance of {@link StreetName }
     * 
     */
    public StreetName createStreetName() {
        return new StreetName();
    }

    /**
     * Create an instance of {@link CloseDate }
     * 
     */
    public CloseDate createCloseDate() {
        return new CloseDate();
    }

    /**
     * Create an instance of {@link ListPrice }
     * 
     */
    public ListPrice createListPrice() {
        return new ListPrice();
    }

    /**
     * Create an instance of {@link REOffice }
     * 
     */
    public REOffice createREOffice() {
        return new REOffice();
    }

    /**
     * Create an instance of {@link ProspectModificationTimestamp }
     * 
     */
    public ProspectModificationTimestamp createProspectModificationTimestamp() {
        return new ProspectModificationTimestamp();
    }

    /**
     * Create an instance of {@link ProspectPropertyQuery }
     * 
     */
    public ProspectPropertyQuery createProspectPropertyQuery() {
        return new ProspectPropertyQuery();
    }

    /**
     * Create an instance of {@link REPropHistory }
     * 
     */
    public REPropHistory createREPropHistory() {
        return new REPropHistory();
    }

    /**
     * Create an instance of {@link REPropEntry }
     * 
     */
    public REPropEntry createREPropEntry() {
        return new REPropEntry();
    }

    /**
     * Create an instance of {@link Latitude }
     * 
     */
    public Latitude createLatitude() {
        return new Latitude();
    }

    /**
     * Create an instance of {@link ClosePrice }
     * 
     */
    public ClosePrice createClosePrice() {
        return new ClosePrice();
    }

    /**
     * Create an instance of {@link REData }
     * 
     */
    public REData createREData() {
        return new REData();
    }

    /**
     * Create an instance of {@link REProperties }
     * 
     */
    public REProperties createREProperties() {
        return new REProperties();
    }

    /**
     * Create an instance of {@link REOffices }
     * 
     */
    public REOffices createREOffices() {
        return new REOffices();
    }

    /**
     * Create an instance of {@link REAgents }
     * 
     */
    public REAgents createREAgents() {
        return new REAgents();
    }

    /**
     * Create an instance of {@link REOfficeRosters }
     * 
     */
    public REOfficeRosters createREOfficeRosters() {
        return new REOfficeRosters();
    }

    /**
     * Create an instance of {@link REProspects }
     * 
     */
    public REProspects createREProspects() {
        return new REProspects();
    }

    /**
     * Create an instance of {@link REActivities }
     * 
     */
    public REActivities createREActivities() {
        return new REActivities();
    }

    /**
     * Create an instance of {@link REHistories }
     * 
     */
    public REHistories createREHistories() {
        return new REHistories();
    }

    /**
     * Create an instance of {@link REPublicRecords }
     * 
     */
    public REPublicRecords createREPublicRecords() {
        return new REPublicRecords();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link ListingID }
     * 
     */
    public ListingID createListingID() {
        return new ListingID();
    }

    /**
     * Create an instance of {@link Listing }
     * 
     */
    public Listing createListing() {
        return new Listing();
    }

    /**
     * Create an instance of {@link SalesData }
     * 
     */
    public SalesData createSalesData() {
        return new SalesData();
    }

    /**
     * Create an instance of {@link ContractDate }
     * 
     */
    public ContractDate createContractDate() {
        return new ContractDate();
    }

    /**
     * Create an instance of {@link Commission }
     * 
     */
    public Commission createCommission() {
        return new Commission();
    }

    /**
     * Create an instance of {@link DaysOnMarket }
     * 
     */
    public DaysOnMarket createDaysOnMarket() {
        return new DaysOnMarket();
    }

    /**
     * Create an instance of {@link AssociationFee }
     * 
     */
    public AssociationFee createAssociationFee() {
        return new AssociationFee();
    }

    /**
     * Create an instance of {@link StreetNumber }
     * 
     */
    public StreetNumber createStreetNumber() {
        return new StreetNumber();
    }

    /**
     * Create an instance of {@link BoxNumber }
     * 
     */
    public BoxNumber createBoxNumber() {
        return new BoxNumber();
    }

    /**
     * Create an instance of {@link StreetAdditionalInfo }
     * 
     */
    public StreetAdditionalInfo createStreetAdditionalInfo() {
        return new StreetAdditionalInfo();
    }

    /**
     * Create an instance of {@link StreetDirSuffix }
     * 
     */
    public StreetDirSuffix createStreetDirSuffix() {
        return new StreetDirSuffix();
    }

    /**
     * Create an instance of {@link StreetSuffix }
     * 
     */
    public StreetSuffix createStreetSuffix() {
        return new StreetSuffix();
    }

    /**
     * Create an instance of {@link UnitNumber }
     * 
     */
    public UnitNumber createUnitNumber() {
        return new UnitNumber();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link StateOrProvince }
     * 
     */
    public StateOrProvince createStateOrProvince() {
        return new StateOrProvince();
    }

    /**
     * Create an instance of {@link PostalCode }
     * 
     */
    public PostalCode createPostalCode() {
        return new PostalCode();
    }

    /**
     * Create an instance of {@link Unstructured }
     * 
     */
    public Unstructured createUnstructured() {
        return new Unstructured();
    }

    /**
     * Create an instance of {@link TotalUnits }
     * 
     */
    public TotalUnits createTotalUnits() {
        return new TotalUnits();
    }

    /**
     * Create an instance of {@link MortgageAmount }
     * 
     */
    public MortgageAmount createMortgageAmount() {
        return new MortgageAmount();
    }

    /**
     * Create an instance of {@link AssessedValuation }
     * 
     */
    public AssessedValuation createAssessedValuation() {
        return new AssessedValuation();
    }

    /**
     * Create an instance of {@link ChangeType }
     * 
     */
    public ChangeType createChangeType() {
        return new ChangeType();
    }

    /**
     * Create an instance of {@link ExpirationDate }
     * 
     */
    public ExpirationDate createExpirationDate() {
        return new ExpirationDate();
    }

    /**
     * Create an instance of {@link ProfOptions }
     * 
     */
    public ProfOptions createProfOptions() {
        return new ProfOptions();
    }

    /**
     * Create an instance of {@link CommonInterest }
     * 
     */
    public CommonInterest createCommonInterest() {
        return new CommonInterest();
    }

    /**
     * Create an instance of {@link ResidentialProperty }
     * 
     */
    public ResidentialProperty createResidentialProperty() {
        return new ResidentialProperty();
    }

    /**
     * Create an instance of {@link Complex }
     * 
     */
    public Complex createComplex() {
        return new Complex();
    }

    /**
     * Create an instance of {@link Bedrooms }
     * 
     */
    public Bedrooms createBedrooms() {
        return new Bedrooms();
    }

    /**
     * Create an instance of {@link Baths }
     * 
     */
    public Baths createBaths() {
        return new Baths();
    }

    /**
     * Create an instance of {@link LivingArea }
     * 
     */
    public LivingArea createLivingArea() {
        return new LivingArea();
    }

    /**
     * Create an instance of {@link LotSize }
     * 
     */
    public LotSize createLotSize() {
        return new LotSize();
    }

    /**
     * Create an instance of {@link Stories }
     * 
     */
    public Stories createStories() {
        return new Stories();
    }

    /**
     * Create an instance of {@link YearBuilt }
     * 
     */
    public YearBuilt createYearBuilt() {
        return new YearBuilt();
    }

    /**
     * Create an instance of {@link Heating }
     * 
     */
    public Heating createHeating() {
        return new Heating();
    }

    /**
     * Create an instance of {@link Cooling }
     * 
     */
    public Cooling createCooling() {
        return new Cooling();
    }

    /**
     * Create an instance of {@link Pool }
     * 
     */
    public Pool createPool() {
        return new Pool();
    }

    /**
     * Create an instance of {@link Occupant }
     * 
     */
    public Occupant createOccupant() {
        return new Occupant();
    }

    /**
     * Create an instance of {@link WaterFront }
     * 
     */
    public WaterFront createWaterFront() {
        return new WaterFront();
    }

    /**
     * Create an instance of {@link Fireplaces }
     * 
     */
    public Fireplaces createFireplaces() {
        return new Fireplaces();
    }

    /**
     * Create an instance of {@link ListingData }
     * 
     */
    public ListingData createListingData() {
        return new ListingData();
    }

    /**
     * Create an instance of {@link ActivityStatus }
     * 
     */
    public ActivityStatus createActivityStatus() {
        return new ActivityStatus();
    }

    /**
     * Create an instance of {@link BathsThreeQuarter }
     * 
     */
    public BathsThreeQuarter createBathsThreeQuarter() {
        return new BathsThreeQuarter();
    }

    /**
     * Create an instance of {@link NetIncome }
     * 
     */
    public NetIncome createNetIncome() {
        return new NetIncome();
    }

    /**
     * Create an instance of {@link Longitude }
     * 
     */
    public Longitude createLongitude() {
        return new Longitude();
    }

    /**
     * Create an instance of {@link PropertyRecord }
     * 
     */
    public PropertyRecord createPropertyRecord() {
        return new PropertyRecord();
    }

    /**
     * Create an instance of {@link LotsAndLand }
     * 
     */
    public LotsAndLand createLotsAndLand() {
        return new LotsAndLand();
    }

    /**
     * Create an instance of {@link MultiFamily }
     * 
     */
    public MultiFamily createMultiFamily() {
        return new MultiFamily();
    }

    /**
     * Create an instance of {@link REActivity }
     * 
     */
    public REActivity createREActivity() {
        return new REActivity();
    }

    /**
     * Create an instance of {@link ProspectAgent }
     * 
     */
    public ProspectAgent createProspectAgent() {
        return new ProspectAgent();
    }

    /**
     * Create an instance of {@link REOfficeRoster }
     * 
     */
    public REOfficeRoster createREOfficeRoster() {
        return new REOfficeRoster();
    }

    /**
     * Create an instance of {@link RETax }
     * 
     */
    public RETax createRETax() {
        return new RETax();
    }

    /**
     * Create an instance of {@link ParcelLocation }
     * 
     */
    public ParcelLocation createParcelLocation() {
        return new ParcelLocation();
    }

    /**
     * Create an instance of {@link ParcelOwner }
     * 
     */
    public ParcelOwner createParcelOwner() {
        return new ParcelOwner();
    }

    /**
     * Create an instance of {@link TaxTransactionData }
     * 
     */
    public TaxTransactionData createTaxTransactionData() {
        return new TaxTransactionData();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Participants }
     * 
     */
    public Participants createParticipants() {
        return new Participants();
    }

    /**
     * Create an instance of {@link ProfDetails }
     * 
     */
    public ProfDetails createProfDetails() {
        return new ProfDetails();
    }

    /**
     * Create an instance of {@link EntryOffice }
     * 
     */
    public EntryOffice createEntryOffice() {
        return new EntryOffice();
    }

    /**
     * Create an instance of {@link TaxData }
     * 
     */
    public TaxData createTaxData() {
        return new TaxData();
    }

    /**
     * Create an instance of {@link GrossIncome }
     * 
     */
    public GrossIncome createGrossIncome() {
        return new GrossIncome();
    }

    /**
     * Create an instance of {@link ProfSequence }
     * 
     */
    public ProfSequence createProfSequence() {
        return new ProfSequence();
    }

    /**
     * Create an instance of {@link ActivityOffice }
     * 
     */
    public ActivityOffice createActivityOffice() {
        return new ActivityOffice();
    }

    /**
     * Create an instance of {@link VacancyFactor }
     * 
     */
    public VacancyFactor createVacancyFactor() {
        return new VacancyFactor();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link MLSInformation }
     * 
     */
    public MLSInformation createMLSInformation() {
        return new MLSInformation();
    }

    /**
     * Create an instance of {@link ListingStatus }
     * 
     */
    public ListingStatus createListingStatus() {
        return new ListingStatus();
    }

    /**
     * Create an instance of {@link OriginalListPrice }
     * 
     */
    public OriginalListPrice createOriginalListPrice() {
        return new OriginalListPrice();
    }

    /**
     * Create an instance of {@link StatusChangeDate }
     * 
     */
    public StatusChangeDate createStatusChangeDate() {
        return new StatusChangeDate();
    }

    /**
     * Create an instance of {@link Ownership }
     * 
     */
    public Ownership createOwnership() {
        return new Ownership();
    }

    /**
     * Create an instance of {@link BathsHalf }
     * 
     */
    public BathsHalf createBathsHalf() {
        return new BathsHalf();
    }

    /**
     * Create an instance of {@link BathsTotal }
     * 
     */
    public BathsTotal createBathsTotal() {
        return new BathsTotal();
    }

    /**
     * Create an instance of {@link BathsFull }
     * 
     */
    public BathsFull createBathsFull() {
        return new BathsFull();
    }

    /**
     * Create an instance of {@link REProspect }
     * 
     */
    public REProspect createREProspect() {
        return new REProspect();
    }

    /**
     * Create an instance of {@link ProspectPropertyClass }
     * 
     */
    public ProspectPropertyClass createProspectPropertyClass() {
        return new ProspectPropertyClass();
    }

    /**
     * Create an instance of {@link ProspectOffice }
     * 
     */
    public ProspectOffice createProspectOffice() {
        return new ProspectOffice();
    }

    /**
     * Create an instance of {@link ProspectUsedTimestamp }
     * 
     */
    public ProspectUsedTimestamp createProspectUsedTimestamp() {
        return new ProspectUsedTimestamp();
    }

    /**
     * Create an instance of {@link PictureData }
     * 
     */
    public PictureData createPictureData() {
        return new PictureData();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link EntryAgent }
     * 
     */
    public EntryAgent createEntryAgent() {
        return new EntryAgent();
    }

    /**
     * Create an instance of {@link MailingAddress }
     * 
     */
    public MailingAddress createMailingAddress() {
        return new MailingAddress();
    }

    /**
     * Create an instance of {@link DocumentDate }
     * 
     */
    public DocumentDate createDocumentDate() {
        return new DocumentDate();
    }

    /**
     * Create an instance of {@link StartDateTime }
     * 
     */
    public StartDateTime createStartDateTime() {
        return new StartDateTime();
    }

    /**
     * Create an instance of {@link SchoolData }
     * 
     */
    public SchoolData createSchoolData() {
        return new SchoolData();
    }

    /**
     * Create an instance of {@link ActivityAgent }
     * 
     */
    public ActivityAgent createActivityAgent() {
        return new ActivityAgent();
    }

    /**
     * Create an instance of {@link GeographicData }
     * 
     */
    public GeographicData createGeographicData() {
        return new GeographicData();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

}
