//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "garage",
    "carPort",
    "openParking",
    "coveredParking"
})
@XmlRootElement(name = "Parking")
public class Parking {

    @XmlElement(name = "Garage")
    protected Garage garage;
    @XmlElement(name = "CarPort")
    protected CarPort carPort;
    @XmlElement(name = "OpenParking")
    protected OpenParking openParking;
    @XmlElement(name = "CoveredParking")
    protected CoveredParking coveredParking;

    /**
     * Gets the value of the garage property.
     * 
     * @return
     *     possible object is
     *     {@link Garage }
     *     
     */
    public Garage getGarage() {
        return garage;
    }

    /**
     * Sets the value of the garage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Garage }
     *     
     */
    public void setGarage(Garage value) {
        this.garage = value;
    }

    /**
     * Gets the value of the carPort property.
     * 
     * @return
     *     possible object is
     *     {@link CarPort }
     *     
     */
    public CarPort getCarPort() {
        return carPort;
    }

    /**
     * Sets the value of the carPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarPort }
     *     
     */
    public void setCarPort(CarPort value) {
        this.carPort = value;
    }

    /**
     * Gets the value of the openParking property.
     * 
     * @return
     *     possible object is
     *     {@link OpenParking }
     *     
     */
    public OpenParking getOpenParking() {
        return openParking;
    }

    /**
     * Sets the value of the openParking property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenParking }
     *     
     */
    public void setOpenParking(OpenParking value) {
        this.openParking = value;
    }

    /**
     * Gets the value of the coveredParking property.
     * 
     * @return
     *     possible object is
     *     {@link CoveredParking }
     *     
     */
    public CoveredParking getCoveredParking() {
        return coveredParking;
    }

    /**
     * Sets the value of the coveredParking property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoveredParking }
     *     
     */
    public void setCoveredParking(CoveredParking value) {
        this.coveredParking = value;
    }

}
