//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "ProfOptions")
public class ProfOptions {

    @XmlAttribute(name = "Lunch")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lunch;
    @XmlAttribute(name = "Refreshments")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refreshments;
    @XmlValue
    protected String value;

    /**
     * Gets the value of the lunch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLunch() {
        if (lunch == null) {
            return "No";
        } else {
            return lunch;
        }
    }

    /**
     * Sets the value of the lunch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLunch(String value) {
        this.lunch = value;
    }

    /**
     * Gets the value of the refreshments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefreshments() {
        if (refreshments == null) {
            return "No";
        } else {
            return refreshments;
        }
    }

    /**
     * Sets the value of the refreshments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefreshments(String value) {
        this.refreshments = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getvalue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setvalue(String value) {
        this.value = value;
    }

}
