//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "copyrightNotice",
    "disclaimer",
    "residentialProperty",
    "commonInterest",
    "lotsAndLand",
    "multiFamily",
    "taxData"
})
@XmlRootElement(name = "REProperties")
public class REProperties {

    @XmlElement(name = "CopyrightNotice")
    protected String copyrightNotice;
    @XmlElement(name = "Disclaimer")
    protected String disclaimer;
    @XmlElement(name = "ResidentialProperty")
    protected List<ResidentialProperty> residentialProperty;
    @XmlElement(name = "CommonInterest")
    protected List<CommonInterest> commonInterest;
    @XmlElement(name = "LotsAndLand")
    protected List<LotsAndLand> lotsAndLand;
    @XmlElement(name = "MultiFamily")
    protected List<MultiFamily> multiFamily;
    @XmlElement(name = "TaxData")
    protected List<TaxData> taxData;

    /**
     * Gets the value of the copyrightNotice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightNotice() {
        return copyrightNotice;
    }

    /**
     * Sets the value of the copyrightNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightNotice(String value) {
        this.copyrightNotice = value;
    }

    /**
     * Gets the value of the disclaimer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimer() {
        return disclaimer;
    }

    /**
     * Sets the value of the disclaimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimer(String value) {
        this.disclaimer = value;
    }

    /**
     * Gets the value of the residentialProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the residentialProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResidentialProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResidentialProperty }
     * 
     * 
     */
    public List<ResidentialProperty> getResidentialProperty() {
        if (residentialProperty == null) {
            residentialProperty = new ArrayList<ResidentialProperty>();
        }
        return this.residentialProperty;
    }

    /**
     * Gets the value of the commonInterest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commonInterest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommonInterest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommonInterest }
     * 
     * 
     */
    public List<CommonInterest> getCommonInterest() {
        if (commonInterest == null) {
            commonInterest = new ArrayList<CommonInterest>();
        }
        return this.commonInterest;
    }

    /**
     * Gets the value of the lotsAndLand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lotsAndLand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLotsAndLand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LotsAndLand }
     * 
     * 
     */
    public List<LotsAndLand> getLotsAndLand() {
        if (lotsAndLand == null) {
            lotsAndLand = new ArrayList<LotsAndLand>();
        }
        return this.lotsAndLand;
    }

    /**
     * Gets the value of the multiFamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiFamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiFamily }
     * 
     * 
     */
    public List<MultiFamily> getMultiFamily() {
        if (multiFamily == null) {
            multiFamily = new ArrayList<MultiFamily>();
        }
        return this.multiFamily;
    }

    /**
     * Gets the value of the taxData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxData }
     * 
     * 
     */
    public List<TaxData> getTaxData() {
        if (taxData == null) {
            taxData = new ArrayList<TaxData>();
        }
        return this.taxData;
    }

}
