//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prospectID",
    "prospectPublicName",
    "prospectPropertyClass",
    "prospectPropertyQuery",
    "prospectAgent",
    "prospectOffice",
    "prospectModificationTimestamp",
    "prospectUsedTimestamp"
})
@XmlRootElement(name = "REProspect")
public class REProspect {

    @XmlElement(name = "ProspectID")
    protected String prospectID;
    @XmlElement(name = "ProspectPublicName")
    protected String prospectPublicName;
    @XmlElement(name = "ProspectPropertyClass")
    protected ProspectPropertyClass prospectPropertyClass;
    @XmlElement(name = "ProspectPropertyQuery")
    protected ProspectPropertyQuery prospectPropertyQuery;
    @XmlElement(name = "ProspectAgent")
    protected ProspectAgent prospectAgent;
    @XmlElement(name = "ProspectOffice")
    protected ProspectOffice prospectOffice;
    @XmlElement(name = "ProspectModificationTimestamp")
    protected ProspectModificationTimestamp prospectModificationTimestamp;
    @XmlElement(name = "ProspectUsedTimestamp")
    protected ProspectUsedTimestamp prospectUsedTimestamp;

    /**
     * Gets the value of the prospectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProspectID() {
        return prospectID;
    }

    /**
     * Sets the value of the prospectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProspectID(String value) {
        this.prospectID = value;
    }

    /**
     * Gets the value of the prospectPublicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProspectPublicName() {
        return prospectPublicName;
    }

    /**
     * Sets the value of the prospectPublicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProspectPublicName(String value) {
        this.prospectPublicName = value;
    }

    /**
     * Gets the value of the prospectPropertyClass property.
     * 
     * @return
     *     possible object is
     *     {@link ProspectPropertyClass }
     *     
     */
    public ProspectPropertyClass getProspectPropertyClass() {
        return prospectPropertyClass;
    }

    /**
     * Sets the value of the prospectPropertyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProspectPropertyClass }
     *     
     */
    public void setProspectPropertyClass(ProspectPropertyClass value) {
        this.prospectPropertyClass = value;
    }

    /**
     * Gets the value of the prospectPropertyQuery property.
     * 
     * @return
     *     possible object is
     *     {@link ProspectPropertyQuery }
     *     
     */
    public ProspectPropertyQuery getProspectPropertyQuery() {
        return prospectPropertyQuery;
    }

    /**
     * Sets the value of the prospectPropertyQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProspectPropertyQuery }
     *     
     */
    public void setProspectPropertyQuery(ProspectPropertyQuery value) {
        this.prospectPropertyQuery = value;
    }

    /**
     * Gets the value of the prospectAgent property.
     * 
     * @return
     *     possible object is
     *     {@link ProspectAgent }
     *     
     */
    public ProspectAgent getProspectAgent() {
        return prospectAgent;
    }

    /**
     * Sets the value of the prospectAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProspectAgent }
     *     
     */
    public void setProspectAgent(ProspectAgent value) {
        this.prospectAgent = value;
    }

    /**
     * Gets the value of the prospectOffice property.
     * 
     * @return
     *     possible object is
     *     {@link ProspectOffice }
     *     
     */
    public ProspectOffice getProspectOffice() {
        return prospectOffice;
    }

    /**
     * Sets the value of the prospectOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProspectOffice }
     *     
     */
    public void setProspectOffice(ProspectOffice value) {
        this.prospectOffice = value;
    }

    /**
     * Gets the value of the prospectModificationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link ProspectModificationTimestamp }
     *     
     */
    public ProspectModificationTimestamp getProspectModificationTimestamp() {
        return prospectModificationTimestamp;
    }

    /**
     * Sets the value of the prospectModificationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProspectModificationTimestamp }
     *     
     */
    public void setProspectModificationTimestamp(ProspectModificationTimestamp value) {
        this.prospectModificationTimestamp = value;
    }

    /**
     * Gets the value of the prospectUsedTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link ProspectUsedTimestamp }
     *     
     */
    public ProspectUsedTimestamp getProspectUsedTimestamp() {
        return prospectUsedTimestamp;
    }

    /**
     * Sets the value of the prospectUsedTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProspectUsedTimestamp }
     *     
     */
    public void setProspectUsedTimestamp(ProspectUsedTimestamp value) {
        this.prospectUsedTimestamp = value;
    }

}
