//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listing",
    "bedrooms",
    "baths",
    "subdivision",
    "associationFee",
    "livingArea",
    "lotSize",
    "parking",
    "stories",
    "yearBuilt",
    "heating",
    "cooling",
    "pool",
    "interiorFeatures",
    "exteriorFeatures",
    "type",
    "style",
    "rooms",
    "occupant",
    "waterFront",
    "fireplaces",
    "roof",
    "exterior"
})
@XmlRootElement(name = "ResidentialProperty")
public class ResidentialProperty {

    @XmlElement(name = "Listing")
    protected Listing listing;
    @XmlElement(name = "Bedrooms")
    protected Bedrooms bedrooms;
    @XmlElement(name = "Baths")
    protected Baths baths;
    @XmlElement(name = "Subdivision")
    protected String subdivision;
    @XmlElement(name = "AssociationFee")
    protected AssociationFee associationFee;
    @XmlElement(name = "LivingArea")
    protected LivingArea livingArea;
    @XmlElement(name = "LotSize")
    protected LotSize lotSize;
    @XmlElement(name = "Parking")
    protected Parking parking;
    @XmlElement(name = "Stories")
    protected Stories stories;
    @XmlElement(name = "YearBuilt")
    protected YearBuilt yearBuilt;
    @XmlElement(name = "Heating")
    protected Heating heating;
    @XmlElement(name = "Cooling")
    protected Cooling cooling;
    @XmlElement(name = "Pool")
    protected Pool pool;
    @XmlElement(name = "InteriorFeatures")
    protected String interiorFeatures;
    @XmlElement(name = "ExteriorFeatures")
    protected String exteriorFeatures;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "Style")
    protected String style;
    @XmlElement(name = "Rooms")
    protected Rooms rooms;
    @XmlElement(name = "Occupant")
    protected Occupant occupant;
    @XmlElement(name = "WaterFront")
    protected WaterFront waterFront;
    @XmlElement(name = "Fireplaces")
    protected Fireplaces fireplaces;
    @XmlElement(name = "Roof")
    protected String roof;
    @XmlElement(name = "Exterior")
    protected String exterior;

    /**
     * Gets the value of the listing property.
     * 
     * @return
     *     possible object is
     *     {@link Listing }
     *     
     */
    public Listing getListing() {
        return listing;
    }

    /**
     * Sets the value of the listing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Listing }
     *     
     */
    public void setListing(Listing value) {
        this.listing = value;
    }

    /**
     * Gets the value of the bedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Bedrooms }
     *     
     */
    public Bedrooms getBedrooms() {
        return bedrooms;
    }

    /**
     * Sets the value of the bedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bedrooms }
     *     
     */
    public void setBedrooms(Bedrooms value) {
        this.bedrooms = value;
    }

    /**
     * Gets the value of the baths property.
     * 
     * @return
     *     possible object is
     *     {@link Baths }
     *     
     */
    public Baths getBaths() {
        return baths;
    }

    /**
     * Sets the value of the baths property.
     * 
     * @param value
     *     allowed object is
     *     {@link Baths }
     *     
     */
    public void setBaths(Baths value) {
        this.baths = value;
    }

    /**
     * Gets the value of the subdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdivision() {
        return subdivision;
    }

    /**
     * Sets the value of the subdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdivision(String value) {
        this.subdivision = value;
    }

    /**
     * Gets the value of the associationFee property.
     * 
     * @return
     *     possible object is
     *     {@link AssociationFee }
     *     
     */
    public AssociationFee getAssociationFee() {
        return associationFee;
    }

    /**
     * Sets the value of the associationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociationFee }
     *     
     */
    public void setAssociationFee(AssociationFee value) {
        this.associationFee = value;
    }

    /**
     * Gets the value of the livingArea property.
     * 
     * @return
     *     possible object is
     *     {@link LivingArea }
     *     
     */
    public LivingArea getLivingArea() {
        return livingArea;
    }

    /**
     * Sets the value of the livingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link LivingArea }
     *     
     */
    public void setLivingArea(LivingArea value) {
        this.livingArea = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link LotSize }
     *     
     */
    public LotSize getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotSize }
     *     
     */
    public void setLotSize(LotSize value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     * @return
     *     possible object is
     *     {@link Parking }
     *     
     */
    public Parking getParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parking }
     *     
     */
    public void setParking(Parking value) {
        this.parking = value;
    }

    /**
     * Gets the value of the stories property.
     * 
     * @return
     *     possible object is
     *     {@link Stories }
     *     
     */
    public Stories getStories() {
        return stories;
    }

    /**
     * Sets the value of the stories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stories }
     *     
     */
    public void setStories(Stories value) {
        this.stories = value;
    }

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link YearBuilt }
     *     
     */
    public YearBuilt getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearBuilt }
     *     
     */
    public void setYearBuilt(YearBuilt value) {
        this.yearBuilt = value;
    }

    /**
     * Gets the value of the heating property.
     * 
     * @return
     *     possible object is
     *     {@link Heating }
     *     
     */
    public Heating getHeating() {
        return heating;
    }

    /**
     * Sets the value of the heating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heating }
     *     
     */
    public void setHeating(Heating value) {
        this.heating = value;
    }

    /**
     * Gets the value of the cooling property.
     * 
     * @return
     *     possible object is
     *     {@link Cooling }
     *     
     */
    public Cooling getCooling() {
        return cooling;
    }

    /**
     * Sets the value of the cooling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cooling }
     *     
     */
    public void setCooling(Cooling value) {
        this.cooling = value;
    }

    /**
     * Gets the value of the pool property.
     * 
     * @return
     *     possible object is
     *     {@link Pool }
     *     
     */
    public Pool getPool() {
        return pool;
    }

    /**
     * Sets the value of the pool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pool }
     *     
     */
    public void setPool(Pool value) {
        this.pool = value;
    }

    /**
     * Gets the value of the interiorFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteriorFeatures() {
        return interiorFeatures;
    }

    /**
     * Sets the value of the interiorFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteriorFeatures(String value) {
        this.interiorFeatures = value;
    }

    /**
     * Gets the value of the exteriorFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExteriorFeatures() {
        return exteriorFeatures;
    }

    /**
     * Sets the value of the exteriorFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExteriorFeatures(String value) {
        this.exteriorFeatures = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link Rooms }
     *     
     */
    public Rooms getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rooms }
     *     
     */
    public void setRooms(Rooms value) {
        this.rooms = value;
    }

    /**
     * Gets the value of the occupant property.
     * 
     * @return
     *     possible object is
     *     {@link Occupant }
     *     
     */
    public Occupant getOccupant() {
        return occupant;
    }

    /**
     * Sets the value of the occupant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Occupant }
     *     
     */
    public void setOccupant(Occupant value) {
        this.occupant = value;
    }

    /**
     * Gets the value of the waterFront property.
     * 
     * @return
     *     possible object is
     *     {@link WaterFront }
     *     
     */
    public WaterFront getWaterFront() {
        return waterFront;
    }

    /**
     * Sets the value of the waterFront property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaterFront }
     *     
     */
    public void setWaterFront(WaterFront value) {
        this.waterFront = value;
    }

    /**
     * Gets the value of the fireplaces property.
     * 
     * @return
     *     possible object is
     *     {@link Fireplaces }
     *     
     */
    public Fireplaces getFireplaces() {
        return fireplaces;
    }

    /**
     * Sets the value of the fireplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fireplaces }
     *     
     */
    public void setFireplaces(Fireplaces value) {
        this.fireplaces = value;
    }

    /**
     * Gets the value of the roof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoof() {
        return roof;
    }

    /**
     * Sets the value of the roof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoof(String value) {
        this.roof = value;
    }

    /**
     * Gets the value of the exterior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExterior() {
        return exterior;
    }

    /**
     * Sets the value of the exterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExterior(String value) {
        this.exterior = value;
    }

}
