//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxKey",
    "taxID",
    "county",
    "parcelLocation",
    "parcelOwner",
    "taxTransactionData",
    "assessedValuation",
    "propertyZoning",
    "parcelMapURL",
    "modificationTimestamp"
})
@XmlRootElement(name = "RETax")
public class RETax {

    @XmlElement(name = "TaxKey")
    protected String taxKey;
    @XmlElement(name = "TaxID")
    protected String taxID;
    @XmlElement(name = "County")
    protected String county;
    @XmlElement(name = "ParcelLocation")
    protected ParcelLocation parcelLocation;
    @XmlElement(name = "ParcelOwner")
    protected ParcelOwner parcelOwner;
    @XmlElement(name = "TaxTransactionData")
    protected List<TaxTransactionData> taxTransactionData;
    @XmlElement(name = "AssessedValuation")
    protected AssessedValuation assessedValuation;
    @XmlElement(name = "PropertyZoning")
    protected String propertyZoning;
    @XmlElement(name = "ParcelMapURL")
    protected String parcelMapURL;
    @XmlElement(name = "ModificationTimestamp")
    protected ModificationTimestamp modificationTimestamp;

    /**
     * Gets the value of the taxKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxKey() {
        return taxKey;
    }

    /**
     * Sets the value of the taxKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxKey(String value) {
        this.taxKey = value;
    }

    /**
     * Gets the value of the taxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxID() {
        return taxID;
    }

    /**
     * Sets the value of the taxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxID(String value) {
        this.taxID = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the parcelLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ParcelLocation }
     *     
     */
    public ParcelLocation getParcelLocation() {
        return parcelLocation;
    }

    /**
     * Sets the value of the parcelLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParcelLocation }
     *     
     */
    public void setParcelLocation(ParcelLocation value) {
        this.parcelLocation = value;
    }

    /**
     * Gets the value of the parcelOwner property.
     * 
     * @return
     *     possible object is
     *     {@link ParcelOwner }
     *     
     */
    public ParcelOwner getParcelOwner() {
        return parcelOwner;
    }

    /**
     * Sets the value of the parcelOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParcelOwner }
     *     
     */
    public void setParcelOwner(ParcelOwner value) {
        this.parcelOwner = value;
    }

    /**
     * Gets the value of the taxTransactionData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxTransactionData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxTransactionData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxTransactionData }
     * 
     * 
     */
    public List<TaxTransactionData> getTaxTransactionData() {
        if (taxTransactionData == null) {
            taxTransactionData = new ArrayList<TaxTransactionData>();
        }
        return this.taxTransactionData;
    }

    /**
     * Gets the value of the assessedValuation property.
     * 
     * @return
     *     possible object is
     *     {@link AssessedValuation }
     *     
     */
    public AssessedValuation getAssessedValuation() {
        return assessedValuation;
    }

    /**
     * Sets the value of the assessedValuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessedValuation }
     *     
     */
    public void setAssessedValuation(AssessedValuation value) {
        this.assessedValuation = value;
    }

    /**
     * Gets the value of the propertyZoning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyZoning() {
        return propertyZoning;
    }

    /**
     * Sets the value of the propertyZoning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyZoning(String value) {
        this.propertyZoning = value;
    }

    /**
     * Gets the value of the parcelMapURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelMapURL() {
        return parcelMapURL;
    }

    /**
     * Sets the value of the parcelMapURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelMapURL(String value) {
        this.parcelMapURL = value;
    }

    /**
     * Gets the value of the modificationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationTimestamp }
     *     
     */
    public ModificationTimestamp getModificationTimestamp() {
        return modificationTimestamp;
    }

    /**
     * Sets the value of the modificationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationTimestamp }
     *     
     */
    public void setModificationTimestamp(ModificationTimestamp value) {
        this.modificationTimestamp = value;
    }

}
