//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diningRoom",
    "livingRoom",
    "familyRoom",
    "basement",
    "totalRooms"
})
@XmlRootElement(name = "Rooms")
public class Rooms {

    @XmlElement(name = "DiningRoom")
    protected DiningRoom diningRoom;
    @XmlElement(name = "LivingRoom")
    protected LivingRoom livingRoom;
    @XmlElement(name = "FamilyRoom")
    protected FamilyRoom familyRoom;
    @XmlElement(name = "Basement")
    protected Basement basement;
    @XmlElement(name = "TotalRooms")
    protected TotalRooms totalRooms;

    /**
     * Gets the value of the diningRoom property.
     * 
     * @return
     *     possible object is
     *     {@link DiningRoom }
     *     
     */
    public DiningRoom getDiningRoom() {
        return diningRoom;
    }

    /**
     * Sets the value of the diningRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiningRoom }
     *     
     */
    public void setDiningRoom(DiningRoom value) {
        this.diningRoom = value;
    }

    /**
     * Gets the value of the livingRoom property.
     * 
     * @return
     *     possible object is
     *     {@link LivingRoom }
     *     
     */
    public LivingRoom getLivingRoom() {
        return livingRoom;
    }

    /**
     * Sets the value of the livingRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link LivingRoom }
     *     
     */
    public void setLivingRoom(LivingRoom value) {
        this.livingRoom = value;
    }

    /**
     * Gets the value of the familyRoom property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyRoom }
     *     
     */
    public FamilyRoom getFamilyRoom() {
        return familyRoom;
    }

    /**
     * Sets the value of the familyRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyRoom }
     *     
     */
    public void setFamilyRoom(FamilyRoom value) {
        this.familyRoom = value;
    }

    /**
     * Gets the value of the basement property.
     * 
     * @return
     *     possible object is
     *     {@link Basement }
     *     
     */
    public Basement getBasement() {
        return basement;
    }

    /**
     * Sets the value of the basement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Basement }
     *     
     */
    public void setBasement(Basement value) {
        this.basement = value;
    }

    /**
     * Gets the value of the totalRooms property.
     * 
     * @return
     *     possible object is
     *     {@link TotalRooms }
     *     
     */
    public TotalRooms getTotalRooms() {
        return totalRooms;
    }

    /**
     * Sets the value of the totalRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalRooms }
     *     
     */
    public void setTotalRooms(TotalRooms value) {
        this.totalRooms = value;
    }

}
