//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reAgent",
    "reOffice",
    "contractDate",
    "closePrice",
    "closeDate"
})
@XmlRootElement(name = "SalesData")
public class SalesData {

    @XmlElement(name = "REAgent")
    protected List<REAgent> reAgent;
    @XmlElement(name = "REOffice")
    protected REOffice reOffice;
    @XmlElement(name = "ContractDate")
    protected ContractDate contractDate;
    @XmlElement(name = "ClosePrice")
    protected ClosePrice closePrice;
    @XmlElement(name = "CloseDate")
    protected CloseDate closeDate;

    /**
     * Gets the value of the reAgent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reAgent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREAgent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REAgent }
     * 
     * 
     */
    public List<REAgent> getREAgent() {
        if (reAgent == null) {
            reAgent = new ArrayList<REAgent>();
        }
        return this.reAgent;
    }

    /**
     * Gets the value of the reOffice property.
     * 
     * @return
     *     possible object is
     *     {@link REOffice }
     *     
     */
    public REOffice getREOffice() {
        return reOffice;
    }

    /**
     * Sets the value of the reOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link REOffice }
     *     
     */
    public void setREOffice(REOffice value) {
        this.reOffice = value;
    }

    /**
     * Gets the value of the contractDate property.
     * 
     * @return
     *     possible object is
     *     {@link ContractDate }
     *     
     */
    public ContractDate getContractDate() {
        return contractDate;
    }

    /**
     * Sets the value of the contractDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractDate }
     *     
     */
    public void setContractDate(ContractDate value) {
        this.contractDate = value;
    }

    /**
     * Gets the value of the closePrice property.
     * 
     * @return
     *     possible object is
     *     {@link ClosePrice }
     *     
     */
    public ClosePrice getClosePrice() {
        return closePrice;
    }

    /**
     * Sets the value of the closePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClosePrice }
     *     
     */
    public void setClosePrice(ClosePrice value) {
        this.closePrice = value;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link CloseDate }
     *     
     */
    public CloseDate getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseDate }
     *     
     */
    public void setCloseDate(CloseDate value) {
        this.closeDate = value;
    }

}
