//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured"
})
@XmlRootElement(name = "StreetAddress")
public class StreetAddress {

    @XmlElements({
        @XmlElement(name = "StreetNumber", type = StreetNumber.class),
        @XmlElement(name = "BoxNumber", type = BoxNumber.class),
        @XmlElement(name = "StreetDirPrefix", type = StreetDirPrefix.class),
        @XmlElement(name = "StreetName", type = StreetName.class),
        @XmlElement(name = "StreetAdditionalInfo", type = StreetAdditionalInfo.class),
        @XmlElement(name = "StreetDirSuffix", type = StreetDirSuffix.class),
        @XmlElement(name = "StreetSuffix", type = StreetSuffix.class),
        @XmlElement(name = "UnitNumber", type = UnitNumber.class),
        @XmlElement(name = "City", type = City.class),
        @XmlElement(name = "StateOrProvince", type = StateOrProvince.class),
        @XmlElement(name = "Country", type = Country.class),
        @XmlElement(name = "PostalCode", type = PostalCode.class),
        @XmlElement(name = "CarrierRoute", type = CarrierRoute.class),
        @XmlElement(name = "Unstructured", type = Unstructured.class)
    })
    protected List<Object> streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured;

    /**
     * Gets the value of the streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreetNumber }
     * {@link BoxNumber }
     * {@link StreetDirPrefix }
     * {@link StreetName }
     * {@link StreetAdditionalInfo }
     * {@link StreetDirSuffix }
     * {@link StreetSuffix }
     * {@link UnitNumber }
     * {@link City }
     * {@link StateOrProvince }
     * {@link Country }
     * {@link PostalCode }
     * {@link CarrierRoute }
     * {@link Unstructured }
     * 
     * 
     */
    public List<Object> getStreetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured() {
        if (streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured == null) {
            streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured = new ArrayList<Object>();
        }
        return this.streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured;
    }
    
  /*  public String getCorrectAddresss(){
    	return this.streetNumberOrBoxNumberOrStreetDirPrefixOrStreetNameOrStreetAdditionalInfoOrStreetDirSuffixOrStreetSuffixOrUnitNumberOrCityOrStateOrProvinceOrCountryOrPostalCodeOrCarrierRouteOrUnstructured
    }*/

}
