//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentID",
    "documentDate",
    "documentType",
    "transactionType",
    "closePrice",
    "closeDate",
    "vestmentType",
    "mortgageAmount"
})
@XmlRootElement(name = "TaxTransactionData")
public class TaxTransactionData {

    @XmlElement(name = "DocumentID")
    protected String documentID;
    @XmlElement(name = "DocumentDate")
    protected DocumentDate documentDate;
    @XmlElement(name = "DocumentType")
    protected String documentType;
    @XmlElement(name = "TransactionType")
    protected String transactionType;
    @XmlElement(name = "ClosePrice")
    protected ClosePrice closePrice;
    @XmlElement(name = "CloseDate")
    protected CloseDate closeDate;
    @XmlElement(name = "VestmentType")
    protected String vestmentType;
    @XmlElement(name = "MortgageAmount")
    protected MortgageAmount mortgageAmount;

    /**
     * Gets the value of the documentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the documentDate property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentDate }
     *     
     */
    public DocumentDate getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentDate }
     *     
     */
    public void setDocumentDate(DocumentDate value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the closePrice property.
     * 
     * @return
     *     possible object is
     *     {@link ClosePrice }
     *     
     */
    public ClosePrice getClosePrice() {
        return closePrice;
    }

    /**
     * Sets the value of the closePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClosePrice }
     *     
     */
    public void setClosePrice(ClosePrice value) {
        this.closePrice = value;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link CloseDate }
     *     
     */
    public CloseDate getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseDate }
     *     
     */
    public void setCloseDate(CloseDate value) {
        this.closeDate = value;
    }

    /**
     * Gets the value of the vestmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVestmentType() {
        return vestmentType;
    }

    /**
     * Sets the value of the vestmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVestmentType(String value) {
        this.vestmentType = value;
    }

    /**
     * Gets the value of the mortgageAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MortgageAmount }
     *     
     */
    public MortgageAmount getMortgageAmount() {
        return mortgageAmount;
    }

    /**
     * Sets the value of the mortgageAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MortgageAmount }
     *     
     */
    public void setMortgageAmount(MortgageAmount value) {
        this.mortgageAmount = value;
    }

}
