//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 11:55:46 AM IST 
//


package rets1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bedrooms",
    "baths",
    "rentIncome",
    "associationFee",
    "livingArea",
    "parking",
    "stories",
    "heating",
    "cooling",
    "interiorFeatures",
    "rooms",
    "occupant",
    "fireplaces"
})
@XmlRootElement(name = "Unit")
public class Unit {

    @XmlElement(name = "Bedrooms")
    protected Bedrooms bedrooms;
    @XmlElement(name = "Baths")
    protected Baths baths;
    @XmlElement(name = "RentIncome")
    protected RentIncome rentIncome;
    @XmlElement(name = "AssociationFee")
    protected AssociationFee associationFee;
    @XmlElement(name = "LivingArea")
    protected LivingArea livingArea;
    @XmlElement(name = "Parking")
    protected Parking parking;
    @XmlElement(name = "Stories")
    protected Stories stories;
    @XmlElement(name = "Heating")
    protected Heating heating;
    @XmlElement(name = "Cooling")
    protected Cooling cooling;
    @XmlElement(name = "InteriorFeatures")
    protected String interiorFeatures;
    @XmlElement(name = "Rooms")
    protected Rooms rooms;
    @XmlElement(name = "Occupant")
    protected Occupant occupant;
    @XmlElement(name = "Fireplaces")
    protected Fireplaces fireplaces;

    /**
     * Gets the value of the bedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Bedrooms }
     *     
     */
    public Bedrooms getBedrooms() {
        return bedrooms;
    }

    /**
     * Sets the value of the bedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bedrooms }
     *     
     */
    public void setBedrooms(Bedrooms value) {
        this.bedrooms = value;
    }

    /**
     * Gets the value of the baths property.
     * 
     * @return
     *     possible object is
     *     {@link Baths }
     *     
     */
    public Baths getBaths() {
        return baths;
    }

    /**
     * Sets the value of the baths property.
     * 
     * @param value
     *     allowed object is
     *     {@link Baths }
     *     
     */
    public void setBaths(Baths value) {
        this.baths = value;
    }

    /**
     * Gets the value of the rentIncome property.
     * 
     * @return
     *     possible object is
     *     {@link RentIncome }
     *     
     */
    public RentIncome getRentIncome() {
        return rentIncome;
    }

    /**
     * Sets the value of the rentIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link RentIncome }
     *     
     */
    public void setRentIncome(RentIncome value) {
        this.rentIncome = value;
    }

    /**
     * Gets the value of the associationFee property.
     * 
     * @return
     *     possible object is
     *     {@link AssociationFee }
     *     
     */
    public AssociationFee getAssociationFee() {
        return associationFee;
    }

    /**
     * Sets the value of the associationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociationFee }
     *     
     */
    public void setAssociationFee(AssociationFee value) {
        this.associationFee = value;
    }

    /**
     * Gets the value of the livingArea property.
     * 
     * @return
     *     possible object is
     *     {@link LivingArea }
     *     
     */
    public LivingArea getLivingArea() {
        return livingArea;
    }

    /**
     * Sets the value of the livingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link LivingArea }
     *     
     */
    public void setLivingArea(LivingArea value) {
        this.livingArea = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     * @return
     *     possible object is
     *     {@link Parking }
     *     
     */
    public Parking getParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parking }
     *     
     */
    public void setParking(Parking value) {
        this.parking = value;
    }

    /**
     * Gets the value of the stories property.
     * 
     * @return
     *     possible object is
     *     {@link Stories }
     *     
     */
    public Stories getStories() {
        return stories;
    }

    /**
     * Sets the value of the stories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stories }
     *     
     */
    public void setStories(Stories value) {
        this.stories = value;
    }

    /**
     * Gets the value of the heating property.
     * 
     * @return
     *     possible object is
     *     {@link Heating }
     *     
     */
    public Heating getHeating() {
        return heating;
    }

    /**
     * Sets the value of the heating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heating }
     *     
     */
    public void setHeating(Heating value) {
        this.heating = value;
    }

    /**
     * Gets the value of the cooling property.
     * 
     * @return
     *     possible object is
     *     {@link Cooling }
     *     
     */
    public Cooling getCooling() {
        return cooling;
    }

    /**
     * Sets the value of the cooling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cooling }
     *     
     */
    public void setCooling(Cooling value) {
        this.cooling = value;
    }

    /**
     * Gets the value of the interiorFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteriorFeatures() {
        return interiorFeatures;
    }

    /**
     * Sets the value of the interiorFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteriorFeatures(String value) {
        this.interiorFeatures = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link Rooms }
     *     
     */
    public Rooms getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rooms }
     *     
     */
    public void setRooms(Rooms value) {
        this.rooms = value;
    }

    /**
     * Gets the value of the occupant property.
     * 
     * @return
     *     possible object is
     *     {@link Occupant }
     *     
     */
    public Occupant getOccupant() {
        return occupant;
    }

    /**
     * Sets the value of the occupant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Occupant }
     *     
     */
    public void setOccupant(Occupant value) {
        this.occupant = value;
    }

    /**
     * Gets the value of the fireplaces property.
     * 
     * @return
     *     possible object is
     *     {@link Fireplaces }
     *     
     */
    public Fireplaces getFireplaces() {
        return fireplaces;
    }

    /**
     * Sets the value of the fireplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fireplaces }
     *     
     */
    public void setFireplaces(Fireplaces value) {
        this.fireplaces = value;
    }

}
